config/routes.rb
Rails.application.routes.draw do

  get 'expert_sessions/new'

  get 'experts_signup' => 'experts#new' 
  get 'sessions/new'

  root 'users#home'
  get 'signup' => 'users#new'

  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'  

  get 'experts_login' => 'expert_sessions#new'
  post 'experts_login' => 'expert_sessions#create'
  delete 'experts_logout' => 'expert_sessions#destroy'

  get 'dashboard/:id' => 'experts#dashboard', as: 'dashboard'

  

  resources :users do
    resources :transactions
  end
  

  resources :experts
  resources :tags, only: [:index, :show]
  resources :available_times
end

app/controllers/expert_sessions_controller.rb
class ExpertSessionsController < ApplicationController
  
  def new
  end

  def create
    expert = Expert.find_by(email: params[:session][:email].downcase)
    if expert && expert.authenticate(params[:session][:password])
      log_in_expert expert
      #params[:session][:remember_me] == '1' ? remember(expert) : forget(expert)
      redirect_to dashboard_path(expert)
    else
      flash.now[:danger] = 'Invalid email/password combination'
      render 'new'
    end
  end

  def destroy
    log_out_expert
    redirect_to root_path
  end
end

app/helpers/expert_sessions_helper.rb
module ExpertSessionsHelper

  include SessionsHelper

  def log_in_expert(expert)
    session[:expert_id] = expert.id
  end

  def current_expert
    @current_expert ||= Expert.find_by(id: session[:expert_id])
  end 

  def logged_in_expert?
    !current_expert.nil?
  end   

  def log_out_expert
    session.delete(:expert_id)
    @current_expert = nil
  end  
end

app/views/expert_sessions/new.html.erb
<div class="dash-title">
  <div class="title text-center">
    <h3>Experts Login</h3>
  </div>
</div>

<div>  
  <div class="row">
    <div class="col-xs-4 col-xs-offset-4 col-md-4 col-md-offset-4 square">
    <%= render 'layouts/messages' %>    
      </br>
      <%= form_for(:session, url: experts_login_path) do |f| %>
        <%= f.label :email %>
        <%= f.email_field :email, class: 'form-control' %>

        <%= f.label :password %>
        <%= f.password_field :password, class: 'form-control' %>
        
        <%= f.label :remember_me, class: "checkbox inline" do %>
          <%= f.check_box :remember_me %>
          <span>Remember me on this computer</span>
        <% end %>
        </br>
        <%= f.submit "Login", class: "btn" %>
      <% end %>
      </br>
      <p>Do you want to become a mentor? <%= link_to "Sign up now!", experts_signup_path %></p>
    </div>
  </div>
</div>

</br>
</br>