config/routes.rb
Rails.application.routes.draw do

  get 'expert_sessions/new'

  get 'experts_signup' => 'experts#new' 
  get 'sessions/new'

  root 'users#home'
  get 'signup' => 'users#new'

  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'  

  get 'experts_login' => 'expert_sessions#new'
  post 'experts_login' => 'expert_sessions#create'
  delete 'experts_logout' => 'expert_sessions#destroy'

  get 'dashboard/:id' => 'experts#dashboard', as: 'dashboard'

  

  resources :users do
    resources :transactions
  end
  

  resources :experts
  resources :tags, only: [:index, :show]
  resources :available_times
end

app/models/user.rb
class User < ActiveRecord::Base

  has_many :transactions
  
  attr_accessor :remember_token

  before_save { self.email = email.downcase }
  validates :firstname, presence: true, length: { maximum: 50 }
  validates :lastname, presence: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }
  validates :location, presence: true

  has_secure_password
  validates :password, presence: true, length: { minimum: 6 }, allow_nil: true

  # Returns the hash digest of the given string.
  def User.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                                                  BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end

  def User.new_token
    SecureRandom.urlsafe_base64
  end

  # Remembers a user in the database for use in persistent sessions.
  def remember
    self.remember_token = User.new_token
    update_attribute(:remember_digest, User.digest(remember_token))
  end  

  # Returns true if the given token matches the digest.
  def authenticated?(remember_token)
    return false if remember_digest.nil?    
    BCrypt::Password.new(remember_digest).is_password?(remember_token)
  end 
 
  # Forgets a user.
  def forget
    update_attribute(:remember_digest, nil)
  end   

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_action :logged_in_user, only: [:edit, :update]
  before_action :correct_user,   only: [:edit, :update]

  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
    @transactions = @user.transactions.order(:date)
    #@ordered_transactions = @transactions.sort_by { |t| AvailableTime.find(t.available_time_id).date }
    #@ordered_transactions = @transactions.sort_by { |t| t.updated_at }
    @pending_transactions = @transactions.where(status: "pending") 
    @confirmed_transactions = @transactions.where(status: "ok").sort_by { |t| AvailableTime.find(t.available_time_id).date }
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      log_in @user
      flash[:success] = "Your account at Codementorship has been created"
      redirect_to user_path(@user)
    else
      render 'new'
    end
  end

  def edit
    @user = User.find(params[:id])    
  end  

  def update
    @user = User.find(params[:id])
    if @user.update_attributes(user_params)
      flash[:success] = "Profile updated"
      redirect_to user_path(@user)
    else
      render 'edit'
    end
  end  

  private

    def user_params
      params.require(:user).permit(:firstname, :lastname, :email, :location, :password,
                                   :password_confirmation)
    end  

    def logged_in_user
      unless logged_in?
        store_location
        flash[:danger] = "Please log in."
        redirect_to login_url
      end
    end    

    def correct_user
      @user = User.find(params[:id])
      redirect_to(root_path) unless current_user?(@user)
    end    
end

app/helpers/users_helper.rb
module UsersHelper
  def gravatar_for(user)
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}"
    image_tag(gravatar_url, alt: user.firstname, class: "gravatar")
  end  
end

app/views/users/edit.html.erb
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <h2>Update your profile</h2>
    <%= form_for(@user) do |f| %>
      <%= render 'shared/user_error_messages' %>

      <%= f.label :firstname %>
      <%= f.text_field :firstname, class: 'form-control' %>
      <%= f.label :lastname %>
      <%= f.text_field :lastname, class: 'form-control' %>      
      <%= f.label :email %>
      <%= f.email_field :email, class: 'form-control' %>

      <%= f.label :location %>
      <%= f.text_field :location, class: 'form-control' %>

      <%= f.label :password %>
      <%= f.password_field :password, class: 'form-control' %>

      <%= f.label :password_confirmation, "Confirmation" %>
      <%= f.password_field :password_confirmation, class: 'form-control' %>

      <%= f.submit "Save changes", class: "btn btn-primary" %>
    <% end %>

    <div class="gravatar_edit">
      <%= gravatar_for @user %>
      <a href="http://gravatar.com/emails" target="_blank">change</a>
    </div>
  </div>
</div>

app/views/users/home.html.erb
<div class="jumbotron">

  <div class="container">
    <h1>Get help of mentors near you</h1>
    <p>Reserve for a class and meet with one of them.</p>
    <div class="row">
      <div class="col-sx-6">
        <%= link_to "Sign Up now", signup_path, class: "btn btn-lg" %>
        <%= link_to "See all mentors", experts_path, class: "btn btn-lg more" %> 
      </div>
    </div>      
  </div><!-- end container -->
</div><!-- end jumbotron -->

<div id="what">
  <div class="container">
    <h3 class="col-xs-12">What is Mentor_code?</h3>
    <div class="row">
      <div class="col-xs-12 col-md-6">
        <p class="lead">Stop feeling lost and start moving in the right direction again.</p>
        <p class="sub-p">We aim to improve education by connecting with the rigth people. If you are an autonomous learner, you are not alone. Seek mentorship, guidance and advice from experts in your field.</p>
        <ul id="items">
          <li>
            <i class="fa fa-users"></i><span>Find programming and web development mentors in your city.</span>
          </li>
          <li >
            <i class="fa fa-calendar"></i>
              <span>Choose your favorite mentor and reserve a time for a class near you.</span>
          </li>
          <li>
            <i class="fa fa-line-chart"></i>
            <span>Get help and support and jumpstart your career!</span>
          </li>
        </ul>
      </div>
      <div class="col-xs-12 col-md-6" id="laptop">
        <%= image_tag("screenshot-macbookair.png")%>
      </div><!-- end col-md-6 -->
    </div><!-- end row -->

  </div><!-- end container-->
  <div class="row">
    <div class="col-xs-12">
      <button href="#" class="btn btn-lg">Learn how it works</button>
    </div>
  </div>
</div><!-- end what -->

<div id="want">
  <div class="text-center">
     <h3>Do you want to meet our mentors?</h3>
     <%= link_to "Meet Mentors", experts_path, class:"btn btn-lg" %>

  </div>
</div>

<div id="get-involved">
  <div class="container homepage">
    <h2>Get Involved</h2>
    <div class="row">
      <div class="col-md-4 involved">
        <span class="fa-stack fa-4x">
          <i class="fa fa-circle fa-stack-2x"></i>
          <i class="fa fa-user fa-stack-1x fa-inverse"></i>
        </span>
        <h3>Students</h3>
        <p>Want to learn how to code? Sign up now to see all the available experts and their schedules and make a reservation for a class!</p>
        <%= link_to "Join us", new_user_path, class:"btn" %>
      </div>
      <div class="col-md-4">
        <span class="fa-stack fa-4x">
          <i class="fa fa-circle fa-stack-2x"></i>
          <i class="fa fa-pencil fa-stack-1x fa-inverse"></i>
        </span>
        <h3>Educators</h3>
        <p>If you want to share your knowledge and help others, mentorship will make you happy. Become a mentor now.</p>
        <%= link_to "Join as a mentor", new_expert_path, class:"btn" %>
      </div>
      <div class="col-md-4">
        <span class="fa-stack fa-4x">
          <i class="fa fa-circle fa-stack-2x"></i>
          <i class="fa fa-money fa-stack-1x fa-inverse"></i>
        </span>
        <h3>Sponsors</h3>
        <p>We love all the support we get to help host more events, and empower more lives with the knowledge of coding. Click to get involved.</p>
        <%= link_to "Give Support", root_path, class:"btn" %>
      </div>
    </div>
  </div> <!-- /container -->
</div>
          

app/views/users/index.html.erb
<h1>All users</h1>
<ul class="users">
	<% @users.each do |user| %>
	  <li><p>User id:<%= user.id %></p></li>
	  <li><p>First name: <%= link_to user.firstname, user_path(user) %></p></li>
	  <li><p>Last name: <%= user.lastname %></p></li>
	  <li><p>Email: <%= user.email %></p></li>
	  <li><p>Location:<%= user.location %></p></li>
	  </br>
	<% end %>
</ul>

app/views/users/new.html.erb
<div class="page-title">
  <div class="title text-center">
    <h3>Create an account</h3>
  </div>
</div>
<div class="row">
  <div class="col-xs-4 col-xs-offset-4 col-md-4 col-md-offset-4 square">
    </br>
    <%= form_for(@user) do |f| %>

      <%= render 'shared/error_messages', object: @user %>

      <div class="form-group">
        <%= f.text_field :firstname, class: 'form-control', placeholder: "First name" %>
      </div><!-- end form-group -->

      <div class="form-group">
        <%= f.text_field :lastname, class: 'form-control', placeholder: "Last name" %>
      </div><!-- end form-group -->     
 
      <div class="form-group">
        <%= f.email_field :email, class: 'form-control', placeholder: "Email" %>
      </div><!-- end form-group -->

      <div class="form-group">
        <%= f.text_field :location, class: 'form-control', placeholder: "Location" %>
      </div><!-- end form-group -->     

      <div class="form-group">
        <%= f.password_field :password, class: 'form-control', placeholder: "Password" %>
      </div><!-- end form-group -->

      <div class="form-group">
        <%= f.password_field :password_confirmation, class: 'form-control', placeholder: "Password Confirmation" %>
      </div><!-- end form-group -->
      </br>
      <%= f.submit "Create my account", class: "btn btn-lg" %>
    <% end %>

  </div>
</div>

</br>
</br>

app/views/users/show.html.erb
<div class="page-title">
  <div class="title text-center">
    <h3>Student Profile</h3>
    <h4><%= @user.firstname %> <%= @user.lastname %></h4>
  </div>
</div><!-- page-title -->

<div>
  <div class="row">
    <div class="col-md-6 col-md-offset-3 structure">
      <div class="row">
        <aside class="col-md-4 col-md-offset-4">
          <section class="user-info">
            <div class="user-gravatar">
              <%= gravatar_for @user %>
            </div>
            <p><%= @user.email %></p>
          </section>
        </aside>
      </div><!-- row -->

      <% if @user.transactions.any? %>
        <p class="center lead"><%= link_to "See all experts", experts_path %></p>
        <div class="panel panel-default">

          <div class="panel-heading center">

            <table class="table table-striped">
            <h3 class="panel-title center"><strong>Your Upcomming Classes</strong></h3>
            <tr class="success">
              <th class= "center">Mentor name:</th>
              <th class= "center">Date:</th>
              <th class= "center">Begins</th>
              <th class= "center">Ends</th>
              <th class= "center">Status</th>
            </tr>
          </div><!-- panel-heading -->

          <div class="panel-body">
            <% @confirmed_transactions.each do |transaction| %>
              
                <tr> 
                  <td>
                    <%= link_to "#{transaction.available_time.expert.firstname} #{transaction.available_time.expert.lastname}", expert_path(transaction.available_time.expert.id) %>
                  </td>
                  <td><%= transaction.available_time.date.strftime("%d/%m/%Y") %> h</td>
                  <td><%= transaction.available_time.start_time.strftime("%H:%M") %> h</td>
                  <td><%= transaction.available_time.end_time.strftime("%H:%M") %> h</td>
                  <% if transaction.status == "ok" %>
                    <td><%= "confirmed" %></td>
                  <% end %>                      
                </tr>
                       
            <% end %>           
            <% @pending_transactions.each do |transaction| %>

                <tr> 
                  <td>
                    <%= link_to "#{transaction.available_time.expert.firstname} #{transaction.available_time.expert.lastname}", expert_path(transaction.available_time.expert.id) %>
                  </td>
                  <td><%= transaction.available_time.date.strftime("%d/%m/%Y") %> h</td>
                  <td><%= transaction.available_time.start_time.strftime("%H:%M") %> h</td>
                  <td><%= transaction.available_time.end_time.strftime("%H:%M") %> h</td>
                  <% if transaction.status == "pending" %>
                    <td style="color: #337AB7"><%= "waiting confirmation" %></td>
                  <% end %>      
                </tr>
                    
            <% end %>           
            </table> 
          </div><!-- end panel-body -->
        </div><!-- panel-default -->

      <% else %>
        <p class="lead text-center"><%= link_to "Choose an expert and make a reservation now!", experts_path %></p>  
      <% end %>

    </div><!-- col-md-6 col-md-offset-3 -->
  </div><!-- row -->
</div>