config/routes.rb
Rails.application.routes.draw do

  get 'expert_sessions/new'

  get 'experts_signup' => 'experts#new' 
  get 'sessions/new'

  root 'users#home'
  get 'signup' => 'users#new'

  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'  

  get 'experts_login' => 'expert_sessions#new'
  post 'experts_login' => 'expert_sessions#create'
  delete 'experts_logout' => 'expert_sessions#destroy'

  get 'dashboard/:id' => 'experts#dashboard', as: 'dashboard'

  

  resources :users do
    resources :transactions
  end
  

  resources :experts
  resources :tags, only: [:index, :show]
  resources :available_times
end

app/views/layouts/_footer.html.erb
<div id="footer" >
  <div class="container">
    <div class="row">
    	<div class="col-sm-8">

        <div id="footer-logo">
    		  <%= image_tag("code.png", :size => "60x60") %>
        </div>
        <div id="footer-logo-2">
          <%= link_to "MENTOR_code", root_path %>
        </div>        
    	</div><!-- end col-sm-8 -->

    	<div class="col-sm-4 text-right">
    		<ul>
    			<li><%= link_to "How it works", root_path %></li>
    			<li><%= link_to "Meet our mentors", experts_path %></li>
    			<li><%= link_to "Login", login_path %></li>
    			<li><%= link_to "Sign up", signup_path %></li>
    		</ul>
    	</div><!-- end col-sm-4 -->
    </div><!-- end row -->  

  </div><!-- end container -->

  <div id="end-footer">
    <div class="container">
    <div class="row">
      <div class="col-md-12">  
          <div class="row">
            <div class="col-sm-4">
              <p>Made by <a>Anaïs Casasayas</a></p>
            </div><!-- end col-sm-4 -->

            <div class="col-sm-8">
              <p>©2015 Anais, LLC | 
              <a href="/terms">Terms</a>
              |
              <a href="/privacy">Privacy</a>
              |  
              <a href="http://twitter.com"><i class="fa fa-twitter"></i></a>
              </p>
            </div><!-- col-sm-8 -->
            
          </div><!-- row --> 
      </div><!-- end end-footer -->
    </div><!-- end row -->  
  </div>  
  </div>  

</div><!-- end footer -->

app/views/layouts/_messages.html.erb
    <% flash.each do |message_type, message| %>
      <div class=" alert alert-<%= message_type %>">
        <%= message %>
      </div>
	  <% end %> 

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <div>
        <%= link_to "MENTOR_code", root_path, class: "navbar-brand pull-left", id: "logo" %>
      </div>
    </div>

    <div class="collapse navbar-collapse">
      <ul class="nav navbar-nav navbar-right">
        <% if logged_in? %>
          <li><%= link_to "See experts", experts_path %></li>
          <li><%= link_to "#{current_user.firstname} #{current_user.lastname} Profile", user_path(current_user) %></li>
          <li><%= link_to "Logout", logout_path, method: "delete" %></li>
        <% elsif logged_in_expert? %>
          <li><%= link_to "#{current_expert.firstname} Dashboard", dashboard_path(current_expert) %></li>
          <li><%= link_to "Logout", experts_logout_path, method: "delete" %></li>
        <% else %>
          <li><%= link_to "Student Login", login_path %></li>
          <li><%= link_to "Are you an expert? Login here", experts_login_path %></li>
        <% end %>
      </ul>

    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>
      <% if logged_in? %>
        Student
      <% elsif logged_in_expert? %>
        Expert
      <% else %>
        Mentor Code
      <% end %>
    </title>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
    <link href='https://fonts.googleapis.com/css?family=Arvo:400,700' rel='stylesheet' type='text/css'>
  </head>
  
  <body data-spy="scroll" data-target=".navbar-collapse" data-offset="50">
    <div>
      <%= render 'layouts/navigation' %>
    	<%= yield %>
    </div>
  </body>
  <footer>
    <%= render 'layouts/footer' %>
  </footer>
</html>